// GERADO por scripts/prepare-media.mjs — não editar à mão.
// As dimensões vêm do arquivo real e alimentam width/height, evitando CLS.

/** Imagem estática do pool. */
export type PoolImage = {
  readonly kind: "image";
  readonly src: string;
  readonly width: number;
  readonly height: number;
};

/**
 * Clipe do pool. Sem áudio de propósito — é decoração da camada da frente do baralho,
 * nunca a única fonte de som da página. `poster` é o que as camadas de trás usam e o
 * que aparece antes do vídeo bufferizar.
 */
export type PoolVideo = {
  readonly kind: "video";
  readonly poster: string;
  readonly webm: string;
  readonly mp4: string;
  readonly width: number;
  readonly height: number;
};

export type PoolItem = PoolImage | PoolVideo;

export const eventsPool: PoolItem[] = [
  { kind: "image", src: "/media/events/events-photographer-press.webp", width: 740, height: 420 },
  { kind: "image", src: "/media/events/events-aniversario-luxuoso.webp", width: 766, height: 400 },
  { kind: "image", src: "/media/events/events-backstage-equipe-production-2.webp", width: 738, height: 416 },
  { kind: "image", src: "/media/events/events-backstage-equipe-production.webp", width: 440, height: 350 },
  { kind: "image", src: "/media/events/events-backstage-equipe-som.webp", width: 833, height: 368 },
  { kind: "image", src: "/media/events/events-cameras-cover-image-2.webp", width: 740, height: 414 },
  { kind: "image", src: "/media/events/events-cameras-cover-image.webp", width: 800, height: 533 },
  { kind: "image", src: "/media/events/events-corporate-apresentacao-slides.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/events/events-corporate-auditorio-cheio.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-conference-craft.webp", width: 1024, height: 573 },
  { kind: "image", src: "/media/events/events-corporate-confraternizacao-equipe.webp", width: 900, height: 506 },
  { kind: "image", src: "/media/events/events-corporate-convencao-empresarial.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-corporate-crachas-recepcao.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-equipe-reuniao.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-event-production-company-4-3.webp", width: 640, height: 480 },
  { kind: "image", src: "/media/events/events-corporate-keynote-palco.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-lancamento-produto.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-networking-coffee.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-painel-discussao.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-corporate-palestra-plateia.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/events/events-corporate-workshop-mesa.webp", width: 900, height: 506 },
  { kind: "image", src: "/media/events/events-dj-dance-road.webp", width: 759, height: 343 },
  { kind: "image", src: "/media/events/events-dj-mixing.webp", width: 706, height: 435 },
  { kind: "image", src: "/media/events/events-fotografo-imprensa-evento.webp", width: 762, height: 468 },
  { kind: "image", src: "/media/events/events-kissing-her-boyfriend.webp", width: 1400, height: 933 },
  { kind: "image", src: "/media/events/events-led-touring-festivals.webp", width: 548, height: 364 },
  { kind: "image", src: "/media/events/events-lighting-sound-technicians-television-operators-work-backstage-public-event.webp", width: 800, height: 534 },
  { kind: "image", src: "/media/events/events-live-performace-indor.webp", width: 740, height: 414 },
  { kind: "image", src: "/media/events/events-photo-couple-cross-1.webp", width: 1400, height: 934 },
  { kind: "image", src: "/media/events/events-photographer-lens.webp", width: 678, height: 452 },
  { kind: "image", src: "/media/events/events-photographer-wedding.webp", width: 648, height: 432 },
  { kind: "image", src: "/media/events/events-production-caixas-som.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-production-camera-filmagem.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-production-dj-console.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-production-equipe-tecnica.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-production-fotografo-evento.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-production-iluminacao-show.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/events/events-production-luzes-led.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-production-mesa-som.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-production-microfone-palco.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-production-mixer-audio.webp", width: 900, height: 506 },
  { kind: "image", src: "/media/events/events-production-palco-montagem.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-production-telao-led.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-amigos-comemorando.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-bolo-aniversario.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-brinde-champanhe.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-convidados-comemorando.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-socials-coroa-debutante.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-debutante-vestido.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/events/events-socials-decoracao-baloes.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-socials-festa-15-anos.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-socials-luzes-festa.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-mesa-doces.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-socials-pista-danca.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-socials-salao-festa.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-stage-lighting.webp", width: 1360, height: 663 },
  { kind: "image", src: "/media/events/events-walking-sunset.webp", width: 1400, height: 933 },
  { kind: "image", src: "/media/events/events-wall-led-1.webp", width: 640, height: 480 },
  { kind: "image", src: "/media/events/events-wall-led-create-show-experience.webp", width: 1080, height: 720 },
  { kind: "image", src: "/media/events/events-weddings-alianca-maos.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/events/events-weddings-altar-flores.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-weddings-brinde-taca.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-weddings-casal-por-do-sol.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/events/events-weddings-casal-retrato.webp", width: 900, height: 1348 },
  { kind: "image", src: "/media/events/events-weddings-cerimonia-ar-livre.webp", width: 1400, height: 2100 },
  { kind: "image", src: "/media/events/events-weddings-convidados-festa.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/events/events-weddings-decoracao-mesa.webp", width: 900, height: 1599 },
  { kind: "image", src: "/media/events/events-weddings-festa-danca.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-weddings-noiva-buque.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/events/events-weddings-noivos-beijo.webp", width: 900, height: 1600 },
  { kind: "image", src: "/media/events/events-weddings-vestido-noiva.webp", width: 900, height: 1353 },
  { kind: "video", poster: "/media/events/events-cople-flipingcamp-poster.webp", webm: "/media/events/events-cople-flipingcamp.webm", mp4: "/media/events/events-cople-flipingcamp.mp4", width: 702, height: 396 },
];

export const companyPool: PoolItem[] = [
  { kind: "image", src: "/media/company/company-brand-campaigns.webp", width: 524, height: 393 },
  { kind: "image", src: "/media/company/company-branding-aplicativo-celular.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/company/company-branding-app-mobile-mao.webp", width: 900, height: 1349 },
  { kind: "image", src: "/media/company/company-branding-campanha-marketing.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-branding-feed-redes-sociais.webp", width: 900, height: 506 },
  { kind: "image", src: "/media/company/company-branding-fotografia-corporativa-equipe.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-branding-google-meu-negocio.webp", width: 900, height: 1347 },
  { kind: "image", src: "/media/company/company-branding-instagram-tela.webp", width: 900, height: 608 },
  { kind: "image", src: "/media/company/company-branding-localizacao-empresa.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/company/company-branding-moodboard-marca.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/company/company-branding-redes-sociais-app.webp", width: 900, height: 543 },
  { kind: "image", src: "/media/company/company-branding-retrato-profissional.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-branding-staff-escritorio.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/company/company-campanhas-publicitarias.webp", width: 404, height: 316 },
  { kind: "image", src: "/media/company/company-content-apresentador-tela.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-content-aula-gravacao.webp", width: 900, height: 1603 },
  { kind: "image", src: "/media/company/company-content-escrita-ebook.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/company/company-content-estudo-notebook.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/company/company-content-gravacao-curso-online.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-content-leitura-livro-digital.webp", width: 900, height: 1349 },
  { kind: "image", src: "/media/company/company-content-material-didatico.webp", width: 900, height: 506 },
  { kind: "image", src: "/media/company/company-content-planejamento-conteudo.webp", width: 900, height: 599 },
  { kind: "image", src: "/media/company/company-content-podcast-microfone.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-content-professor-webcam.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-content-tutorial-camera.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/company/company-content-workshop-online.webp", width: 900, height: 506 },
  { kind: "image", src: "/media/company/company-estudio-fotografico-1.webp", width: 1024, height: 572 },
  { kind: "image", src: "/media/company/company-estudio-fotografico-modelo.webp", width: 1000, height: 661 },
  { kind: "image", src: "/media/company/company-food-image.webp", width: 800, height: 500 },
  { kind: "image", src: "/media/company/company-foto-produto-profissional-studio.webp", width: 747, height: 428 },
  { kind: "image", src: "/media/company/company-gravacao-curso-1.webp", width: 600, height: 338 },
  { kind: "image", src: "/media/company/company-gravacao-curso-2.webp", width: 600, height: 400 },
  { kind: "image", src: "/media/company/company-gravacao-curso-3.webp", width: 600, height: 450 },
  { kind: "image", src: "/media/company/company-lifestyle-product.webp", width: 1400, height: 787 },
  { kind: "image", src: "/media/company/company-maquiagem.webp", width: 678, height: 452 },
  { kind: "image", src: "/media/company/company-perfume-luxo.webp", width: 661, height: 464 },
  { kind: "image", src: "/media/company/company-product-acessorio-still.webp", width: 900, height: 600 },
  { kind: "image", src: "/media/company/company-product-bolsa-still.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-comida-still.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-cosmetico-still.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-eletronico-still.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-embalagem-estudio.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-garrafa-bebida.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-joia-still.webp", width: 900, height: 1347 },
  { kind: "image", src: "/media/company/company-product-luxury-perfum.webp", width: 1400, height: 808 },
  { kind: "image", src: "/media/company/company-product-perfume-estudio.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-relogio-still.webp", width: 900, height: 1350 },
  { kind: "image", src: "/media/company/company-product-roupa-still.webp", width: 900, height: 601 },
  { kind: "image", src: "/media/company/company-product-tenis-estudio.webp", width: 900, height: 1347 },
  { kind: "video", poster: "/media/company/company-commercial-product-soda-poster.webp", webm: "/media/company/company-commercial-product-soda.webm", mp4: "/media/company/company-commercial-product-soda.mp4", width: 540, height: 960 },
  { kind: "video", poster: "/media/company/company-food-restaurant-poster.webp", webm: "/media/company/company-food-restaurant.webm", mp4: "/media/company/company-food-restaurant.mp4", width: 540, height: 960 },
  { kind: "video", poster: "/media/company/company-kindness-reflective-poster.webp", webm: "/media/company/company-kindness-reflective.webm", mp4: "/media/company/company-kindness-reflective.mp4", width: 540, height: 960 },
  { kind: "video", poster: "/media/company/company-luxury-hotel-hospedagem-poster.webp", webm: "/media/company/company-luxury-hotel-hospedagem.webm", mp4: "/media/company/company-luxury-hotel-hospedagem.mp4", width: 540, height: 960 },
  { kind: "video", poster: "/media/company/company-perfum-2-poster.webp", webm: "/media/company/company-perfum-2.webm", mp4: "/media/company/company-perfum-2.mp4", width: 720, height: 900 },
  { kind: "video", poster: "/media/company/company-refined-wood-poster.webp", webm: "/media/company/company-refined-wood.webm", mp4: "/media/company/company-refined-wood.mp4", width: 540, height: 960 },
  { kind: "video", poster: "/media/company/company-web-app-inscricaoflorescer-com-poster.webp", webm: "/media/company/company-web-app-inscricaoflorescer-com.webm", mp4: "/media/company/company-web-app-inscricaoflorescer-com.mp4", width: 370, height: 812 },
  { kind: "video", poster: "/media/company/company-web-app-kaminskilaw-com-poster.webp", webm: "/media/company/company-web-app-kaminskilaw-com.webm", mp4: "/media/company/company-web-app-kaminskilaw-com.mp4", width: 960, height: 456 },
  { kind: "video", poster: "/media/company/company-web-app-nexora-conceitual-poster.webp", webm: "/media/company/company-web-app-nexora-conceitual.webm", mp4: "/media/company/company-web-app-nexora-conceitual.mp4", width: 960, height: 460 },
  { kind: "video", poster: "/media/company/company-web-app-paraisotropicalbr222-com-br-poster.webp", webm: "/media/company/company-web-app-paraisotropicalbr222-com-br.webm", mp4: "/media/company/company-web-app-paraisotropicalbr222-com-br.mp4", width: 960, height: 458 },
  { kind: "video", poster: "/media/company/company-web-app-passoamerica-com-poster.webp", webm: "/media/company/company-web-app-passoamerica-com.webm", mp4: "/media/company/company-web-app-passoamerica-com.mp4", width: 960, height: 458 },
];
